</body>
<?PHP $misteriosoFramework = null; ?>

<br /><br /><br /><br />
<footer>
    <p>Page developed by <a href="https://github.com/misteriosojo/">Misterioso</a></p>

</footer>

<?PHP //if ($_GET['page'] == 'home' || $_GET['page']  == 'bugs') {
//
//echo "<script  type=\"text/javascript\">
//    $( document ).ready(function() {
//        $('#taskNew').circliful();
//        $('#taskDone').circliful();
//        $('#taskToDo').circliful();
//        $('#taskRejected').circliful();
//    });
//</script>";
//
//} ?>

</html>

