<!DOCTYPE html>
<html lang="it">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Misterioso">
    <link rel="shortcut icon" type="image/png" href="theme/img/favicon.png"/>

    <title><?PHP echo $pageTitle ?></title>

    <!-- Bootstrap + mio css -->
    <link rel="stylesheet" href="theme/css/misterioso.css" type="text/css">
    <link rel="stylesheet" href="theme/css/bootstrap.min.css" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>

    <!-- Cerchi dinamici per statistiche -->
    <link href="theme/css/jquery.circliful.css" rel="stylesheet" type="text/css" />
    <link href="theme/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="theme/js/jquery.circliful.min.js"></script>

    <!-- Navbar Example !-->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li id="navHome">
                        <a href="index.php?page=home" title='Homepage'>Home</a>
                    </li>
                    <li id="navProducts">
                        <a href="index.php?page=products" title='List of products'>Products</a>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->

        </div>
    </div>
</head>

<body>
<br />
<div id="logo"></div>
<br />
